#plugin.author:Ankoki
#plugin.url:https://github.com/Ankoki/TE-Prison
#plugin.price:Free
#
dev-debug: false # Only used in development.
Enchants:
  VirtualLaser:
    alias: "§8• §eVirtual Laser"
    description: "Has a chance to virtually break all blocks vertically and horizontally from the triggered block."
    price: 10
    max: 1000
    colour: "106, 255, 0"
    size: 1.5
    blocked-worlds:
      - plots
    event_map:
      BlockBreakEvent: "HIGHEST"